[package]
name = "databend-query"
version = "0.1.0"
description = "A real-time Cloud Distributed Query Engine"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[[bin]]
name = "databend-query"
path = "src/bin/databend-query.rs"

[[bin]]
name = "databend-benchmark"
path = "src/bin/databend-benchmark.rs"

[features]
default = ["simd"]
simd = ["common-arrow/simd"]

[dependencies]
# Workspace dependencies
common-arrow = { path = "../common/arrow" }
common-base = { path = "../common/base" }
common-management = { path = "../common/management" }
common-cache = { path = "../common/cache"}
common-datablocks = { path = "../common/datablocks" }
common-datavalues = { path = "../common/datavalues" }
common-exception = { path = "../common/exception" }
common-functions = { path = "../common/functions" }
common-infallible = { path = "../common/infallible" }
common-planners = { path = "../common/planners" }
common-streams = { path = "../common/streams" }
common-tracing = { path = "../common/tracing" }
common-store-api-sdk= {path = "../common/store-api-sdk" }
common-kv-api = { path = "../common/kv-apis/api" }
common-kv-api-vo = { path = "../common/kv-apis/vo" }
common-meta-api = { path = "../common/meta-apis/api" }
common-meta-api-vo = { path = "../common/meta-apis/vo" }
common-dfs-api = { path = "../common/dfs-apis/api" }
common-dfs-api-vo = { path = "../common/dfs-apis/vo" }
common-io = { path = "../common/io" }
common-metatypes = { path = "../common/metatypes" }
common-clickhouse-srv = { path = "../common/clickhouse-srv" }
common-kv = { path = "../common/kv" }
# Github dependencies
msql-srv = { git = "https://github.com/datafuse-extras/msql-srv", rev = "9c706a3" }
clickhouse-rs = { git = "https://github.com/datafuse-extras/clickhouse-rs", rev = "c4743a9" }
sqlparser = { git = "https://github.com/datafuse-extras/sqlparser-rs", rev = "77f6ae5" }

# Crates.io dependencies
ahash = "0.7.4"
async-trait = "0.1"
async-compat = "0.2.1"
bumpalo = "3.7.1"
bytes = "1"
backtrace = "0.3"
crossbeam = "0.8"
quantiles = "0.7.1"
ctrlc = { version = "3.1.9", features = ["termination"] }
crossbeam-queue = "0.3.2"
env_logger = "0.9"
futures = "0.3"
indexmap = "1.7.0"
lazy_static = "1.4.0"
log = "0.4"
metrics = "0.17.0"
metrics-exporter-prometheus = "0.6.0"
num = "0.4"
nom = "7.0.0"
num_cpus = "1.0"
paste = "^1.0"
pnet = "0.28.0"
chrono-tz = "0.6"
chrono =  "0.4.0"
prost = "0.8.0"
rand = "0.8.4"
rusoto_s3 = "0.47.0"
rusoto_core = "0.47.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.3"
structopt-toml = "0.5.0"
threadpool = "1.8.1"
tokio-stream = { version = "0.1", features = ["net"] }
toml = "0.5.6"
tonic = "0.5.2"
walkdir = "2.3.2"
axum = {version = "0.2.5", features=["headers"] }
uuid = { version = "0.8", features = ["serde", "v4"] }
byteorder = "1"
hyper = "0.14.13"
headers = "0.3.4"
tokio-rustls = "0.22.0"
axum-server = { version = "0.2", features = ["tls-rustls"] }
cargo-license = "0.4.2"
cargo_metadata = "0.14.0"
sha2 = "0.9.8"
sha1 = "0.6.0"

[dependencies.parquet-format-async-temp]
version = "0.2.0"

[dev-dependencies]
pretty_assertions = "0.7"
criterion = "0.3"
mysql = "21.0.1"
reqwest = { version = "0.11", features = ["json", "native-tls"] }
flaky_test = "0.1"
tempfile = "3.2.0"
tower = { version = "0.4", default-features = false, features = ["util", "buffer", "make"] }

[build-dependencies]
common-building = {path = "../common/building"}

[[bench]]
name = "bench_main"
harness = false
